exclude: "^tests/legacy/"
repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile=black"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.5
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        args: ["--strict", "--install-types", "--non-interactive"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
  - repo: local
    hooks:
      - id: prevent-logs
        name: Prevent committing log files
        entry: "bash -c 'if git diff --cached --name-only --diff-filter=ACMRT | grep -E \"\\.log$\"; then echo \"Error: log files detected. Please remove them or add to .gitignore.\"; exit 1; fi'"
        language: system
        pass_filenames: false
