PAGES = [
    {"key": "home", "label": "Home", "roles": ["user", "admin"], "flag": "core"},
    {"key": "chat", "label": "Chat", "roles": ["user", "admin"], "flag": "core"},
    {"key": "personas", "label": "Personas", "roles": ["user", "admin"], "flag": "core"},
    {"key": "memory", "label": "Memory", "roles": ["user", "admin"], "flag": "core"},
    {"key": "files", "label": "Files", "roles": ["user", "admin"], "flag": "core"},
    {"key": "plugins", "label": "Plugins", "roles": ["user", "admin"], "flag": "core"},
    {"key": "settings", "label": "Settings", "roles": ["user", "admin"], "flag": "core"},
    {"key": "calendar", "label": "Calendar", "roles": ["user", "admin"], "flag": "core"},
    {"key": "analytics", "label": "Analytics", "roles": ["admin", "analyst"], "flag": "premium"},
    {"key": "automation", "label": "Automation", "roles": ["user", "admin"], "flag": "premium"},
    {"key": "autonomous", "label": "Autonomous Ops", "roles": ["admin", "devops"], "flag": "premium"},
    {"key": "code_lab", "label": "Code Lab", "roles": ["user", "admin"], "flag": "labs"},
    {"key": "context", "label": "Context", "roles": ["user", "admin"], "flag": "core"},
    {"key": "diagnostics", "label": "Diagnostics", "roles": ["admin"], "flag": "core"},
    {"key": "echo_core", "label": "Echo Core", "roles": ["user", "admin"], "flag": "labs"},
    {"key": "integrations", "label": "Integrations", "roles": ["user", "admin"], "flag": "core"},
    {"key": "iot", "label": "IoT", "roles": ["user", "admin"], "flag": "core"},
    {"key": "labs", "label": "Labs", "roles": ["admin", "devops"], "flag": "labs"},
    {"key": "presence", "label": "Presence", "roles": ["user", "admin"], "flag": "core"},
    {"key": "security", "label": "Security", "roles": ["admin"], "flag": "core"},
    {"key": "task_manager", "label": "Task Manager", "roles": ["admin", "devops"], "flag": "core"},
    {"key": "vision", "label": "Vision", "roles": ["user", "admin"], "flag": "premium"},
    {"key": "voice", "label": "Voice", "roles": ["user", "admin"], "flag": "premium"},
    {"key": "white_label", "label": "White Label", "roles": ["admin"], "flag": "premium"},
    {"key": "workflows", "label": "Workflows", "roles": ["user", "admin"], "flag": "premium"},
    {"key": "admin", "label": "Admin", "roles": ["admin"], "flag": "core"},
]
