"""
Extension Alerting System

This module provides an alerting system for extension monitoring,
supporting various notification channels and escalation levels.
"""

import asyncio
import logging
from datetime import datetime, timedelta
from typing import Dict, List, Any, Optional
from enum import Enum
from dataclasses import dataclass, field

from .extension_error_logging import ErrorSeverity, AlertStatus

logger = logging.getLogger(__name__)

class AlertType(str, Enum):
    """Types of alerts generated by the system."""
    AUTH_FAILURE = "auth_failure"
    PERFORMANCE_DEGRADATION = "performance_degradation"
    SERVICE_DOWN = "service_down"
    RECOVERY_FAILURE = "recovery_failure"
    RECOVERY_SUCCESS = "recovery_success"
    CUSTOM = "custom"

class EscalationLevel(str, Enum):
    """Escalation levels for alerts."""
    LEVEL_1 = "level_1"  # Initial alert
    LEVEL_2 = "level_2"  # Escalate to team
    LEVEL_3 = "level_3"  # Escalate to management
    LEVEL_4 = "level_4"  # Critical escalation

class ExtensionAlertManager:
    """Manages alerts and notifications for extensions."""
    
    def __init__(self):
        self.active_alerts: Dict[str, Dict[str, Any]] = {}
        self.alert_history: List[Dict[str, Any]] = []
        self.monitoring_active = False
        self._monitoring_task: Optional[asyncio.Task] = None
        self.severity_thresholds = {
            ErrorSeverity.LOW: 10,
            ErrorSeverity.MEDIUM: 5,
            ErrorSeverity.HIGH: 1,
            ErrorSeverity.CRITICAL: 1
        }

    async def start_monitoring(self, check_interval: int = 60):
        """Start the alert monitoring loop."""
        if self.monitoring_active:
            return
        
        self.monitoring_active = True
        self._monitoring_task = asyncio.create_task(self._monitoring_loop(check_interval))
        logger.info("Extension alert monitoring started")

    async def stop_monitoring(self):
        """Stop the alert monitoring loop."""
        self.monitoring_active = False
        if self._monitoring_task:
            self._monitoring_task.cancel()
            try:
                await self._monitoring_task
            except asyncio.CancelledError:
                pass
        logger.info("Extension alert monitoring stopped")

    async def _monitoring_loop(self, check_interval: int):
        """Background loop to check for alert conditions."""
        while self.monitoring_active:
            try:
                # Perform periodic health checks or alert re-evaluations here
                await asyncio.sleep(check_interval)
            except asyncio.CancelledError:
                break
            except Exception as e:
                logger.error(f"Error in alert monitoring loop: {e}")
                await asyncio.sleep(check_interval)

    async def create_manual_alert(
        self,
        alert_type: AlertType,
        severity: ErrorSeverity,
        message: str,
        context: Optional[Dict[str, Any]] = None,
        escalation_level: EscalationLevel = EscalationLevel.LEVEL_1
    ) -> str:
        """Create an alert manually."""
        alert_id = f"alert_{int(datetime.utcnow().timestamp())}_{len(self.active_alerts)}"
        
        alert_data = {
            "alert_id": alert_id,
            "type": alert_type.value,
            "severity": severity.value,
            "message": message,
            "context": context or {},
            "escalation_level": escalation_level.value,
            "status": AlertStatus.SENT.value,
            "created_at": datetime.utcnow().isoformat(),
            "updated_at": datetime.utcnow().isoformat()
        }
        
        self.active_alerts[alert_id] = alert_data
        self.alert_history.append(alert_data)
        
        logger.warning(f"Alert created: {message} ({severity.value})")
        return alert_id

    def get_active_alerts(self) -> List[Dict[str, Any]]:
        """Get all currently active alerts."""
        return list(self.active_alerts.values())

    def get_alert_history(self, hours: int = 24) -> List[Dict[str, Any]]:
        """Get alert history for the last N hours."""
        cutoff = datetime.utcnow() - timedelta(hours=hours)
        return [
            alert for alert in self.alert_history 
            if datetime.fromisoformat(alert["created_at"]) >= cutoff
        ]

    def acknowledge_alert(self, alert_id: str, acknowledged_by: str) -> bool:
        """Acknowledge an active alert."""
        if alert_id in self.active_alerts:
            self.active_alerts[alert_id]["status"] = AlertStatus.ACKNOWLEDGED.value
            self.active_alerts[alert_id]["acknowledged_by"] = acknowledged_by
            self.active_alerts[alert_id]["updated_at"] = datetime.utcnow().isoformat()
            return True
        return False

    def resolve_alert(self, alert_id: str, resolved_by: str) -> bool:
        """Resolve an active alert."""
        if alert_id in self.active_alerts:
            alert = self.active_alerts.pop(alert_id)
            alert["status"] = AlertStatus.RESOLVED.value
            alert["resolved_by"] = resolved_by
            alert["updated_at"] = datetime.utcnow().isoformat()
            # History already has the reference if we want to update it there too
            for h_alert in self.alert_history:
                if h_alert["alert_id"] == alert_id:
                    h_alert.update(alert)
                    break
            return True
        return False

# Global instance
extension_alert_manager = ExtensionAlertManager()
