# etcd configuration file
name: etcd-server
data-dir: /etcd
listen-client-urls: http://0.0.0.0:2379
advertise-client-urls: http://milvus-etcd:2379
listen-peer-urls: http://0.0.0.0:2380
initial-advertise-peer-urls: http://milvus-etcd:2380
initial-cluster: etcd-server=http://milvus-etcd:2380
initial-cluster-state: new