profiles:
    default:
      providers:
        chat: llama-cpp
        conversation_processing: llama-cpp
        code: deepseek
        generic: llama-cpp
      fallback: openai
    enterprise:
      providers:
        chat: openai
        conversation_processing: openai
        code: groq
        generic: openai
      fallback: openai
