# Performance Optimization Configuration
# This file defines performance optimization settings for the Kari AI system

# Core optimization settings
enable_performance_optimization: true
deployment_mode: "development"  # minimal, development, production, testing
enable_lazy_loading: true
enable_gpu_offloading: true
enable_service_consolidation: true

# Resource thresholds for automatic optimization
cpu_threshold: 80.0  # Percentage
memory_threshold: 85.0  # Percentage
response_time_threshold: 2.0  # Seconds

# Startup optimization
max_startup_time: 30.0  # Seconds
essential_services_only: false

# Service lifecycle settings
idle_timeout_seconds: 300  # 5 minutes
health_check_interval: 60  # Seconds
max_restart_attempts: 3

# Async processing settings
max_worker_threads: 4
task_queue_size: 1000
enable_parallel_processing: true

# GPU settings
gpu_memory_limit_mb: null  # null for auto-detection
enable_gpu_memory_optimization: true

# Monitoring settings
enable_performance_monitoring: true
metrics_collection_interval: 30  # Seconds
enable_performance_alerts: true

# Logging settings
log_level: "INFO"
enable_performance_logging: true
performance_log_file: "logs/performance.log"

# Advanced settings
enable_service_mesh: false
enable_distributed_processing: false
cache_size_mb: 256

# Deployment-specific overrides
deployment_profiles:
  minimal:
    essential_services_only: true
    enable_lazy_loading: true
    enable_service_consolidation: true
    max_worker_threads: 2
    cache_size_mb: 128
    enable_performance_monitoring: false
    enable_performance_alerts: false
    
  development:
    essential_services_only: false
    enable_lazy_loading: true
    enable_service_consolidation: false
    max_worker_threads: 4
    cache_size_mb: 256
    enable_performance_monitoring: true
    enable_performance_alerts: true
    log_level: "DEBUG"
    
  production:
    essential_services_only: false
    enable_lazy_loading: true
    enable_service_consolidation: true
    max_worker_threads: 8
    cache_size_mb: 512
    enable_performance_monitoring: true
    enable_performance_alerts: true
    cpu_threshold: 70.0
    memory_threshold: 80.0
    response_time_threshold: 1.0
    
  testing:
    essential_services_only: true
    enable_lazy_loading: false
    enable_service_consolidation: false
    max_worker_threads: 2
    cache_size_mb: 64
    enable_performance_monitoring: false
    enable_performance_alerts: false
    log_level: "WARNING"