# Performance Optimization Configuration
# This file defines performance optimization settings for the Kari AI system

# Core optimization settings
enable_performance_optimization: true
deployment_mode: "development"  # minimal, development, production, testing
enable_lazy_loading: true
enable_gpu_offloading: true
enable_service_consolidation: true

# Resource thresholds for automatic optimization
cpu_threshold: 70.0  # Percentage (reduced from 80%)
memory_threshold: 75.0  # Percentage (reduced from 85%)
response_time_threshold: 2.0  # Seconds

# Startup optimization
max_startup_time: 5.0  # Seconds (reduced from 30%)
essential_services_only: true  # Changed to true for development

# Service lifecycle settings
idle_timeout_seconds: 180  # 3 minutes (reduced from 5 minutes)
health_check_interval: 30  # Seconds (reduced from 60)
max_restart_attempts: 3

# Async processing settings
max_worker_threads: 2  # Reduced from 4
task_queue_size: 500  # Reduced from 1000
enable_parallel_processing: true

# GPU settings
gpu_memory_limit_mb: 1024  # Limit GPU memory usage
enable_gpu_memory_optimization: true

# Monitoring settings
enable_performance_monitoring: true
metrics_collection_interval: 60  # Seconds (increased from 30)
enable_performance_alerts: true

# Logging settings
log_level: "INFO"
enable_performance_logging: true
performance_log_file: "logs/performance.log"

# Advanced settings
enable_service_mesh: false
enable_distributed_processing: false
cache_size_mb: 128  # Reduced from 256

# Resource management
enable_automatic_cleanup: true
cleanup_check_interval: 60  # Seconds
memory_pressure_threshold: 1024  # MB
cpu_pressure_threshold: 75.0  # Percentage

# Lazy loading settings
lazy_loading_enabled: true
defer_heavy_services: true
service_timeout_minutes: 5
aggressive_cleanup: true

# Deployment-specific overrides
deployment_profiles:
  minimal:
    essential_services_only: true
    enable_lazy_loading: true
    enable_service_consolidation: true
    max_worker_threads: 1
    cache_size_mb: 64
    enable_performance_monitoring: false
    enable_performance_alerts: false
    idle_timeout_seconds: 120
    memory_threshold: 70.0
    cpu_threshold: 60.0
    
  development:
    essential_services_only: true  # Changed to true
    enable_lazy_loading: true
    enable_service_consolidation: true  # Changed to true
    max_worker_threads: 2  # Reduced from 4
    cache_size_mb: 128  # Reduced from 256
    enable_performance_monitoring: true
    enable_performance_alerts: true
    log_level: "INFO"  # Changed from DEBUG
    idle_timeout_seconds: 180  # Reduced
    memory_threshold: 75.0  # Reduced
    cpu_threshold: 70.0  # Reduced
    
  production:
    essential_services_only: false
    enable_lazy_loading: true
    enable_service_consolidation: true
    max_worker_threads: 8
    cache_size_mb: 512
    enable_performance_monitoring: true
    enable_performance_alerts: true
    cpu_threshold: 70.0
    memory_threshold: 80.0
    response_time_threshold: 1.0
    
  testing:
    essential_services_only: true
    enable_lazy_loading: true  # Changed to true
    enable_service_consolidation: true  # Changed to true
    max_worker_threads: 1  # Reduced from 2
    cache_size_mb: 32  # Reduced from 64
    enable_performance_monitoring: false
    enable_performance_alerts: false
    log_level: "WARNING"