# AI Karen - Production Security Configuration
# This file contains security settings for production deployment

# Content Security Policy
content_security_policy:
  default_src:
    - "'self'"
  script_src:
    - "'self'"
    - "'unsafe-inline'"  # Only if absolutely necessary
    - "https://cdn.jsdelivr.net"
  style_src:
    - "'self'"
    - "'unsafe-inline'"
    - "https://fonts.googleapis.com"
  img_src:
    - "'self'"
    - "data:"
    - "https:"
  connect_src:
    - "'self'"
    - "https://api.your-domain.com"
    - "wss://api.your-domain.com"
  font_src:
    - "'self'"
    - "https://fonts.gstatic.com"
  object_src:
    - "'none'"
  media_src:
    - "'self'"
  frame_src:
    - "'none'"
  base_uri:
    - "'self'"
  form_action:
    - "'self'"
  frame_ancestors:
    - "'none'"
  upgrade_insecure_requests: true

# HTTP Security Headers
security_headers:
  # Strict Transport Security
  strict_transport_security:
    max_age: 31536000  # 1 year
    include_subdomains: true
    preload: true
  
  # X-Frame-Options
  x_frame_options: "DENY"
  
  # X-Content-Type-Options
  x_content_type_options: "nosniff"
  
  # X-XSS-Protection
  x_xss_protection: "1; mode=block"
  
  # Referrer Policy
  referrer_policy: "strict-origin-when-cross-origin"
  
  # Permissions Policy
  permissions_policy:
    camera: "()"
    microphone: "()"
    geolocation: "()"
    payment: "()"
    usb: "()"
    magnetometer: "()"
    gyroscope: "()"
    accelerometer: "()"
    ambient_light_sensor: "()"
    autoplay: "(self)"
    encrypted_media: "(self)"
    fullscreen: "(self)"
    picture_in_picture: "(self)"

# Authentication Security
authentication:
  # Password Policy
  password_policy:
    min_length: 12
    max_length: 128
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special_chars: true
    forbidden_patterns:
      - "password"
      - "123456"
      - "qwerty"
      - "admin"
    max_age_days: 90
    history_count: 12  # Remember last 12 passwords
  
  # Account Lockout
  account_lockout:
    max_attempts: 5
    lockout_duration_minutes: 30
    progressive_delay: true
    notify_admin: true
  
  # Session Security
  session:
    timeout_minutes: 480  # 8 hours
    idle_timeout_minutes: 60
    absolute_timeout_hours: 24
    secure_cookies: true
    httponly_cookies: true
    samesite: "Strict"
    regenerate_on_login: true
    invalidate_on_logout: true
  
  # Two-Factor Authentication
  two_factor:
    enabled: true
    required_for_admin: true
    backup_codes: 10
    totp_window: 1
    rate_limit_attempts: 3

# Rate Limiting
rate_limiting:
  enabled: true
  
  # Global rate limits
  global:
    requests_per_minute: 60
    requests_per_hour: 1000
    requests_per_day: 10000
  
  # Endpoint-specific limits
  endpoints:
    "/api/auth/login":
      requests_per_minute: 5
      requests_per_hour: 20
    "/api/auth/register":
      requests_per_minute: 2
      requests_per_hour: 10
    "/api/chat":
      requests_per_minute: 30
      requests_per_hour: 500
    "/api/admin/*":
      requests_per_minute: 100
      requests_per_hour: 1000
  
  # IP-based limits
  ip_whitelist:
    - "127.0.0.1"
    - "::1"
  
  # Trusted proxies
  trusted_proxies:
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"

# Input Validation
input_validation:
  # Maximum request size
  max_request_size: "50MB"
  max_json_size: "10MB"
  max_form_size: "10MB"
  max_file_size: "100MB"
  
  # Content type validation
  allowed_content_types:
    - "application/json"
    - "application/x-www-form-urlencoded"
    - "multipart/form-data"
    - "text/plain"
  
  # File upload validation
  file_upload:
    allowed_extensions:
      - ".txt"
      - ".pdf"
      - ".doc"
      - ".docx"
      - ".jpg"
      - ".jpeg"
      - ".png"
      - ".gif"
    max_files_per_request: 10
    scan_for_malware: true
    quarantine_suspicious: true

# Data Protection
data_protection:
  # Encryption
  encryption:
    algorithm: "AES-256-GCM"
    key_rotation_days: 90
    encrypt_at_rest: true
    encrypt_in_transit: true
  
  # Data retention
  retention:
    user_data_days: 2555  # 7 years
    log_data_days: 365    # 1 year
    session_data_days: 30
    audit_data_days: 2555 # 7 years
  
  # Privacy
  privacy:
    anonymize_logs: true
    mask_sensitive_data: true
    gdpr_compliance: true
    data_export_enabled: true
    data_deletion_enabled: true

# Network Security
network:
  # TLS Configuration
  tls:
    min_version: "1.2"
    preferred_version: "1.3"
    cipher_suites:
      - "TLS_AES_256_GCM_SHA384"
      - "TLS_CHACHA20_POLY1305_SHA256"
      - "TLS_AES_128_GCM_SHA256"
      - "ECDHE-RSA-AES256-GCM-SHA384"
      - "ECDHE-RSA-AES128-GCM-SHA256"
    hsts_enabled: true
    ocsp_stapling: true
  
  # CORS Configuration
  cors:
    allowed_origins:
      - "https://your-domain.com"
      - "https://www.your-domain.com"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed_headers:
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"
      - "X-CSRF-Token"
    expose_headers:
      - "X-Request-ID"
    credentials: true
    max_age: 86400

# Monitoring and Alerting
security_monitoring:
  # Intrusion Detection
  intrusion_detection:
    enabled: true
    suspicious_patterns:
      - "sql injection"
      - "xss attempt"
      - "path traversal"
      - "command injection"
    block_suspicious_requests: true
    alert_threshold: 5
  
  # Audit Logging
  audit_logging:
    enabled: true
    events:
      - "authentication"
      - "authorization"
      - "data_access"
      - "configuration_change"
      - "admin_action"
      - "security_event"
    log_level: "INFO"
    retention_days: 2555  # 7 years
  
  # Security Alerts
  alerts:
    enabled: true
    channels:
      - "email"
      - "slack"
      - "webhook"
    severity_levels:
      - "critical"
      - "high"
      - "medium"
      - "low"
    escalation_rules:
      critical: "immediate"
      high: "15_minutes"
      medium: "1_hour"
      low: "24_hours"

# Compliance
compliance:
  # Standards
  standards:
    - "SOC2"
    - "ISO27001"
    - "GDPR"
    - "CCPA"
    - "HIPAA"  # If handling health data
  
  # Requirements
  requirements:
    data_classification: true
    access_controls: true
    encryption_standards: true
    audit_trails: true
    incident_response: true
    vulnerability_management: true
    security_training: true

# Incident Response
incident_response:
  # Response Team
  team:
    primary_contact: "security@your-domain.com"
    escalation_contact: "ciso@your-domain.com"
    external_contact: "security-vendor@example.com"
  
  # Response Procedures
  procedures:
    detection_time_minutes: 15
    response_time_minutes: 60
    containment_time_hours: 4
    recovery_time_hours: 24
    lessons_learned_days: 7
  
  # Communication
  communication:
    internal_notification: true
    customer_notification: true
    regulatory_notification: true
    public_disclosure: false  # Unless required by law

# Security Testing
security_testing:
  # Automated Testing
  automated:
    vulnerability_scanning: true
    dependency_scanning: true
    static_code_analysis: true
    dynamic_application_testing: true
    container_scanning: true
  
  # Manual Testing
  manual:
    penetration_testing_frequency: "quarterly"
    code_review_required: true
    security_architecture_review: true
  
  # Bug Bounty
  bug_bounty:
    enabled: false  # Enable if you have a program
    scope: "production"
    rewards: true