
"use client";

import type { ChatMessage } from '@/lib/types';
import { Avatar } from '@/components/ui/avatar';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { User, Bot, Speaker } from 'lucide-react';
import { format } from 'date-fns';
import Image from 'next/image';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip"

interface MessageBubbleProps {
  message: ChatMessage;
}

export function MessageBubble({ message }: MessageBubbleProps) {
  const isUser = message.role === 'user';
  const isSystemMessage = message.role === 'system';

  return (
    <div className={`flex items-start gap-3 my-4 ${isUser ? 'justify-end' : 'justify-start'}`}>
      {!isUser && (
        <Avatar className="h-10 w-10 self-start shrink-0 flex items-center justify-center bg-muted rounded-full">
          <Bot className="h-5 w-5 text-primary" />
        </Avatar>
      )}
      <Card className={`max-w-xl shadow-md rounded-xl ${isUser ? 'bg-primary text-primary-foreground' : 'bg-card'}`}>
        <CardContent className="p-3 md:p-4">
          <div className="flex justify-between items-start">
            <div className="flex-1 space-y-2">
              {message.content && (
                 <p className={`whitespace-pre-wrap text-sm md:text-base ${isSystemMessage ? 'text-foreground' : ''}`}>
                   {message.content}
                 </p>
              )}
              {message.imageDataUri && (
                <div className="mt-2 rounded-lg overflow-hidden border border-border/50">
                    <Image 
                        src={message.imageDataUri}
                        alt="Generated by AI"
                        width={400}
                        height={400}
                        className="object-cover w-full h-auto"
                    />
                </div>
              )}
            </div>
            {!isUser && message.role === 'assistant' && (
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="ml-2 h-7 w-7 text-muted-foreground hover:text-foreground shrink-0"
                      aria-label={"Play message audio"}
                      disabled={true}
                    >
                      <Speaker className="h-4 w-4" />
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>
                    <p>TTS disabled: Backend removed.</p>
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
            )}
          </div>
           <p className={`text-xs mt-2.5 ${isUser ? 'text-primary-foreground/70 text-right' : 'text-muted-foreground text-left'}`}>
            {format(new Date(message.timestamp), 'HH:mm')}
          </p>
        </CardContent>
      </Card>
      {isUser && (
         <Avatar className="h-10 w-10 self-start shrink-0 flex items-center justify-center bg-muted rounded-full">
          <User className="h-5 w-5 text-secondary" />
        </Avatar>
      )}
    </div>
  );
}
