#!/bin/bash
# AI-Karen Backend Startup Script with CORS Fix
# Generated by setup_environment.py

echo "🚀 Starting AI-Karen Backend with CORS Fix"
echo "=" * 45

# Export all required environment variables
export REDIS_PASSWORD="JEmvDv4I17iRY2lJbmWuJOkL"
export POSTGRES_PASSWORD="karen_secure_pass_change_me"
export CORS_ORIGINS="http://localhost:3000,http://localhost:8020,http://localhost:8010,http://10.96.136.74:8010"
export ALLOW_DEV_ORIGINS=true
export CORS_ALLOW_ORIGIN_REGEX='^https?://.*:(\d+)?$'
export AUTH_ALLOW_DEV_LOGIN=true
export AUTH_MODE=development
export ENVIRONMENT=development

echo "🔧 Environment configured:"
echo "   CORS Origins: $CORS_ORIGINS"
echo "   Dev Origins: $ALLOW_DEV_ORIGINS"
echo "   Auth Mode: $AUTH_MODE"
echo ""

echo "🔄 Starting backend..."
python3 start.py
