from __future__ import annotations

from typing import Protocol

from ..models import AssertionNode, EntityNode, GraphEdge, MemoryEventNode


class GraphAdapter(Protocol):
    def initialize(self) -> None: ...
    def upsert_memory_event(self, event: MemoryEventNode) -> None: ...
    def upsert_entity(self, entity: EntityNode) -> None: ...
    def upsert_assertion(self, assertion: AssertionNode) -> None: ...
    def upsert_principal(self, node_type: str, principal_id: str) -> None: ...
    def create_edge(self, edge: GraphEdge) -> None: ...
    def find_related_events(self, tenant_id: str, user_id: str, event_id: str, max_depth: int = 2, limit: int = 20) -> list[dict]: ...
    def find_entity_context(self, tenant_id: str, user_id: str, entity_text: str, limit: int = 20) -> list[dict]: ...
    def close(self) -> None: ...
