apiVersion: apps/v1
kind: Deployment
metadata:
  name: kari
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kari
  template:
    metadata:
      labels:
        app: kari
    spec:
      serviceAccountName: kari
      automountServiceAccountToken: false
      containers:
        - name: kari
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /livez
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
