apiVersion: v1
kind: Service
metadata:
  name: kari
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics/prometheus"
    prometheus.io/port: "{{ .Values.service.port }}"
spec:
  selector:
    app: kari
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
